export const groupStageRanking = [
  { rank: 1, name: "LuisGambino", points: 72, exact: 13, eff: "33.3%", emoji: "🥇" },
  { rank: 2, name: "Salvador_Velasco", points: 63, exact: 10, eff: "29.2%", emoji: "🥈" },
  { rank: 2, name: "Esly Diaz", points: 63, exact: 8, eff: "29.2%", emoji: "🥈" },
  { rank: 4, name: "Final_Nancy", points: 62, exact: 9, eff: "28.7%", emoji: "🏃‍♂️" },
  { rank: 5, name: "Joand_Hernandez", points: 61, exact: 9, eff: "28.2%", emoji: "🏃‍♂️" },
  { rank: 6, name: "Final_Alex Meneses", points: 60, exact: 10, eff: "27.8%", emoji: "🏃‍♂️" },
  { rank: 7, name: "MoisesLeyva_Moyejita", points: 59, exact: 7, eff: "27.3%", emoji: "🏃‍♂️" },
  { rank: 8, name: "Cris_HerreraR (1)", points: 58, exact: 8, eff: "26.9%", emoji: "🏃‍♂️" },
  { rank: 9, name: "Yadira_Estrada_Ganadora", points: 55, exact: 9, eff: "25.5%", emoji: "🏃‍♂️" },
  { rank: 10, name: "Final_GuillermoDG", points: 54, exact: 6, eff: "25.0%", emoji: "🏃‍♂️" },
  { rank: 10, name: "SCampoamorR_Mundial_2026", points: 54, exact: 6, eff: "25.0%", emoji: "🏃‍♂️" },
  { rank: 12, name: "Final_Heidi_QJ", points: 53, exact: 6, eff: "24.5%", emoji: "🏃‍♂️" },
  { rank: 13, name: "Jose Carlos_Aragon", points: 52, exact: 7, eff: "24.1%", emoji: "🏃‍♂️" },
  { rank: 14, name: "Mundial_Efrain_RA", points: 48, exact: 7, eff: "22.2%", emoji: "🏃‍♂️" },
  { rank: 14, name: "Final_GriseldaMP", points: 48, exact: 6, eff: "22.2%", emoji: "🏃‍♂️" },
  { rank: 16, name: "Edith Alejandra Pescador", points: 47, exact: 6, eff: "21.8%", emoji: "🏃‍♂️" },
  { rank: 16, name: "Liliana", points: 47, exact: 6, eff: "21.8%", emoji: "🏃‍♂️" },
  { rank: 18, name: "Arnold_Ronaldo", points: 45, exact: 4, eff: "20.8%", emoji: "🏃‍♂️" },
  { rank: 19, name: "IVAN_MEJIA_ 8905", points: 43, exact: 5, eff: "19.9%", emoji: "🏃‍♂️" },
  { rank: 20, name: "Paloma_Alonso-1", points: 42, exact: 4, eff: "19.4%", emoji: "🏃‍♂️" },
];
